const field_tiep_nhan = {
    NGAY_GOI:"NGAY_GOI",
    GIO_GOI:"GIO_GOI",
    THOI_GIAN_GOI:"THOI_GIAN_GOI",
    SO_DIEN_THOAI:"SO_DIEN_THOAI",
    LOAI_CUOC_GOI:"LOAI_CUOC_GOI",
    BAC_SI_ID:"BAC_SI_ID",
    BENH_NHAN_ID:"BENH_NHAN_ID",
    GHI_CHU_NGUOI_BENH:"GHI_CHU_NGUOI_BENH",
    GHI_CHU_TU_VAN:"GHI_CHU_TU_VAN",
}